In [ ]:
#Importing libraries for data Manipulation and EDA
import numpy as np
import pandas as pd

In [ ]:
#Uploading DataSet
df = pd.read_csv('/content/sample_data/Loan_default.csv')

In [ ]:
df.shape

(255347, 18)

In [ ]:
df.head(6)# looking at first 6 rows to understand the data

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
5,A9S62RQ7US,25,90298,90448,720,18,2,22.72,24,0.10,High School,Unemployed,Single,Yes,No,Business,Yes,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), object(8)
memory usage: 35.1+ MB

In [ ]:
df.describe(include='all')

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
count,255347,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347,255347,255347,255347,255347,255347,255347,255347.000000
unique,255347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,3,2,2,5,2,NaN
top,ZTH91CGL0B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bachelor's,Part-time,Married,Yes,Yes,Business,Yes,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64366,64161,85302,127677,127742,51298,127701,NaN
mean,NaN,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.116128
std,NaN,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.320379
min,NaN,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
max,NaN,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [ ]:
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [ ]:
# Filling the missing numbers with the median (middle value), and missing text with the most common value
df['Income'] = df['Income'].fillna(df['Income'].median())
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())
df['Education'] = df['Education'].fillna(df['Education'].mode()[0])

Check and remove duplicate

In [ ]:
df.duplicated().sum()        # counting exact duplicate rows

np.int64(0)

Distribution and Outlier Check

In [ ]:
# Look at the lowest and highest values to spot anything unrealistic
print(df['Income'].describe())
print(df['LoanAmount'].describe())

count    255347.000000
mean      82499.304597
std       38963.013729
min       15000.000000
25%       48825.500000
50%       82466.000000
75%      116219.000000
max      149999.000000
Name: Income, dtype: float64
count    255347.000000
mean     127578.865512
std       70840.706142
min        5000.000000
25%       66156.000000
50%      127556.000000
75%      188985.000000
max      249999.000000
Name: LoanAmount, dtype: float64

Feature Engineering

In [ ]:
#Step 1: converting yearly interest rate into a monthly rate
monthly_rate = (df['InterestRate'] / 100) / 12

In [ ]:
#Step 2: calculate EMI (monthly loan payment) using the standard EMI formula
df['EMI'] = (df['LoanAmount'] * monthly_rate * (1 + monthly_rate) ** df['LoanTerm']) / \
            ((1 + monthly_rate) ** df['LoanTerm'] - 1)

In [ ]:
# Step 3: EMI as a % of monthly income — shows how much of income goes to loan payment
df['EMI_to_Income'] = (df['EMI'] / (df['Income'] / 12)).round(3)

In [ ]:
# Step 4: group numeric values into easy-to-read bands/categories
df['CreditScoreBand'] = pd.cut(df['CreditScore'], bins=[0, 579, 669, 739, 850],
                                labels=['Poor', 'Fair', 'Good', 'Excellent'])
df['DTIBand'] = pd.cut(df['DTIRatio'], bins=[0, 0.2, 0.4, 0.6, 1],
                        labels=['Low', 'Moderate', 'High', 'Very High'])

In [ ]:
# Step 5: a simple flag for job stability
df['TenureStability'] = np.where(df['MonthsEmployed'] >= 24, 'Stable', 'Unstable')

In [ ]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,...,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,EMI,EMI_to_Income,CreditScoreBand,DTIBand,TenureStability
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,...,Yes,Yes,Other,Yes,0,1759.318045,0.246,Poor,High,Stable
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,...,No,No,Other,Yes,0,2337.519546,0.556,Poor,Very High,Unstable
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,...,Yes,Yes,Auto,No,1,6649.201648,0.948,Poor,Moderate,Stable
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,...,No,No,Business,No,0,2007.188719,0.760,Excellent,Moderate,Unstable
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,...,No,Yes,Auto,No,0,216.773108,0.127,Fair,Very High,Unstable

#Correlation checking

In [ ]:
# Simple correlation table — values closer to 1 or -1 mean a stronger relationship
cols = ['Income', 'LoanAmount', 'CreditScore', 'InterestRate', 'DTIRatio', 'EMI_to_Income', 'Default']
print(df[cols].corr()['Default'].sort_values(ascending=False))

Default          1.000000
EMI_to_Income    0.151862
InterestRate     0.131273
LoanAmount       0.086659
DTIRatio         0.019236
CreditScore     -0.034166
Income          -0.099119
Name: Default, dtype: float64

In [ ]:
df.to_csv('Loan_default_cleanset.csv', index=False)

In [ ]:
from google.colab import files
files.download('Loan_default_cleanset.csv')